# Generated by Django 4.2.29 on 2026-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('alert_id', models.CharField(max_length=200)),
                ('object_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('magnitude', models.FloatField(null=True)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stream_name', 'timestamp'], name='tom_alertst_stream__a592d5_idx')],
            },
        ),
    ]
