# Generated by Django 4.2.29 on 2026-03-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alertstreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='flux',
            field=models.FloatField(null=True),
        ),
    ]
